[[session]]
name = "Home ğŸ "
path = "~/"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "ranger"

[[session]]
name = "Repos ğŸ“¦"
path = "~/Repos/"
startup_command = "ls"

[[session]]
name = "Sandboxes ğŸ–"
path = "~/Playground/"
startup_command = "ls"

[[session]]
name = "Epitech ğŸ“"
path = "~/Epitech/"
startup_command = "ls"

[[session]]
name = "GoAsie ğŸ“¦"
path = "~/Repos/goasie/"

[[session]]
name = "Config ğŸ› "
path = "~/.config/"
statup_command = "la"

[[session]]
name = "LazyVim config ğŸ› "
path = "~/.config/nvim/"
startup_command = "nvim"

[[session]]
name = "Bspwm config ğŸ› "
path = "~/.config/bspwm/"
startup_command = "la"

[[session]]
name = "Sesh config ğŸ› "
path = "~/.config/sesh/"
startup_command = "nvim"

[[session]]
name = "Tmux config ğŸ› "
path = "~/.config/tmux/"
startup_command = "nvim"
