[[session]]
name = "Home ğŸ "
path = "~/"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "ranger"

[[session]]
name = "Repos ğŸ“¦"
path = "~/Repos/"
startup_command = "ls"

[[session]]
name = "Obsidian ğŸ“š"
path = "~/Obsidian/"
startup_command = 'nvim "Knowledge hub.md"'
[[session]]
name = "Sandboxes ğŸ–"
path = "~/Sandboxes/"
startup_command = "ls"

[[session]]
name = "Epitech ğŸ“"
path = "~/Epitech/"
startup_command = "ls"

[[session]]
name = "GoAsie ğŸ“¦"
path = "~/Repos/goasie/"

[[session]]
name = "Config ğŸ› "
path = "~/.config/"
statup_command = "la"

[[session]]
name = "LazyVim config ğŸ› "
path = "~/.config/nvim/"
startup_command = "nvim"

[[session]]
name = "Sesh config ğŸ› "
path = "~/.config/sesh/"
startup_command = "nvim sesh.toml"

[[session]]
name = "Tmux config ğŸ› "
path = "~/.config/tmux/"
startup_command = "nvim tmux.conf"

[[session]]
name = "Ghostty config ğŸ› "
path = "~/.config/ghostty/"
startup_command = "nvim config"

[[session]]
name = "Ghostty themes ğŸ¨"
path = "~/.config/ghostty/themes/"
startup_command = "nvim"
